Feature/lottery admin page
jonaslozys/simoona pull request #9
Opened 2019-10-14 16:03 UTC by jonaslozys

Added a page for managing lotteries, the admin is displayed a page of lotteries with the option to create new one or edit existing ones.

2019-10-15 22:12 UTC, eitvydastamosiunas requested changes
I have written comments on the lines I have some doubts. Overall the commits are good. Only small cosmetic things or bloated code was seen. if you agree with the comment, please fix the code if you don't agree, reply to the comment.

2019-10-15 22:12 UTC, eitvydastamosiunas commented on src/webapp/src/client/app/lotteries/lottery-list.controller.js
> +        ]}
I assume this is just mocked data for testing purpose? I am right?

2019-10-15 22:12 UTC, eitvydastamosiunas commented on src/webapp/src/client/app/lotteries/lotteries.module.js
> +                    ]
Could you explain the purpose of having authorizeOneOfPermissions? Does this mean if user has at least one role from array, user will be able to see list of lotteries?

2019-10-15 22:12 UTC, eitvydastamosiunas commented on src/webapp/src/client/app/lotteries/lottery-list.html
> +            <ace-item-list-filter filter-value="filter.s" on-filtering="onSearch"></ace-item-list-filter>
filter property name "s" looks bit weird. Try to avoid short and missunderstandable property names.

2019-10-15 22:12 UTC, eitvydastamosiunas commented on src/api/Main/DataLayer/Shrooms.EntityModels/Models/Lottery/Lottery.cs
> +    public class Lottery : ImageBaseModel
Strange Inherit. It would be better to inherit BaseModelWithOrg instead of ImageBaseModel. 

ImageCollection type can be added as property of the class.

2019-10-15 22:12 UTC, eitvydastamosiunas commented on src/api/Main/DataLayer/Shrooms.EntityModels/Models/Lottery/ImageBaseModel.cs
> +}
Check my comment on 'src/api/Main/DataLayer/Shrooms.EntityModels/Models/Lottery/Lottery.cs' class.

2019-10-15 22:12 UTC, eitvydastamosiunas commented on src/webapp/src/client/app/lotteries/lottery-manage.controller.js
> +        }
Would pass vm.states to SetTitleScope function and do an conditional comparison inside this function.

        setTitleScope(vm.states);

        function setTitleScope(states) {
            $scope.titleEdit = states.isEdit;
            $scope.titleCreate = states.isCreate;
            
           if (states.isEdit) {
                $rootScope.pageTitle = 'role.editRole';
             } else { 
                $rootScope.pageTitle = 'role.createRole';
             }
        }

2019-10-15 22:12 UTC, eitvydastamosiunas commented on src/webapp/src/client/app/lotteries/lottery-list.controller.js
> +        })
Does it displays statuses in English only?

2019-10-15 22:12 UTC, eitvydastamosiunas commented on src/webapp/src/client/app/lotteries/lottery-manage.controller.js
> +    function lotteryManageController($scope, $state, lotteryFactory, $rootScope, notifySrv, $q, localeSrv, errorHandler, lotteryStatus, lottery) {
What is $q?

2019-10-15 22:12 UTC, eitvydastamosiunas commented on src/webapp/src/client/app/lotteries/lottery-manage.controller.js
> +            vm.isDrafted = vm.lottery.status === lotteryStatus.Drafted;
Do you really vm.isDrafted as you have two other properties which defines vm.states.isEdit and vm.isStarted?
I don't see any usage of vm.isDrafted.

"vm.states.isEdit && !vm.isStarted" is opposite to "vm.states.isEdit && vm.isStarted"

2019-10-15 22:12 UTC, eitvydastamosiunas commented on src/webapp/src/client/app/lotteries/lottery-manage.controller.js
> +                        $state.go('^.List');
Reuse updateSuccess(translation) function by passing string property which is used inside:
localeSrv.formatTranslation(translation, { one: 'lotteries.entityNameSingular', two: vm.lottery.title }));

2019-10-15 22:12 UTC, eitvydastamosiunas commented on src/webapp/src/client/app/lotteries/lottery-list.html
> +                            <a ng-if="lottery.status !== 3" ui-sref="Root.WithOrg.Admin.Lotteries.Edit({ lotteryId : lottery.id})" class="btn btn-default glyphicon glyphicon-pencil" title="{{'common.
Use enum instead of integer

2019-10-15 22:12 UTC, eitvydastamosiunas commented on src/webapp/src/client/app/lotteries/lotteries.repository.js
> +            return $resource(url + 'Delete').delete({id}).$promise;
Are we deleting lottery from database table or we are just changing status of the lottery? I assume that "Delete" is not the right name.

2019-10-15 22:12 UTC, eitvydastamosiunas commented on src/webapp/src/client/app/lotteries/lottery-list.controller.js
> +        })
Would be nice to have an global app-settings.js file which holds all constants in one place instead of having them scattered across various solution files. Suggestion, not complain :)

2019-10-15 22:12 UTC, eitvydastamosiunas commented on src/webapp/src/client/app/lotteries/lottery-list.controller.js
> +            vm.filters.s = searchString;
vm.filters.s => vm.filters.searchString / much more understandable.

2019-10-15 22:12 UTC, eitvydastamosiunas commented on src/webapp/src/client/app/lotteries/lottery-list.html
> +                            {{lottery.endDate.replace('T', '  ').substring(0, lottery.endDate.length - 3)}}
Is loterry.endDate is string not date? If it is string the best way would be to convert it to date and then covert to string by passing the format. 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString

2019-10-15 22:12 UTC, eitvydastamosiunas commented on src/webapp/src/client/app/lotteries/lottery-list.controller.js
> +        .constant('editableLotteries', [3, 4])
Enum values instead of integers.

2019-10-16 09:37 UTC, jonaslozys commented on src/webapp/src/client/app/lotteries/lottery-list.controller.js
> +        ]}
Yeah, it is removed in further commits.

2019-10-16 09:45 UTC, jonaslozys commented on src/api/Main/DataLayer/Shrooms.EntityModels/Models/Lottery/Lottery.cs
> +    public class Lottery : ImageBaseModel
We fixed this unnecessary inheritance in other branch.

2019-10-16 10:21 UTC, jonaslozys commented on src/webapp/src/client/app/lotteries/lottery-manage.controller.js
> +    function lotteryManageController($scope, $state, lotteryFactory, $rootScope, notifySrv, $q, localeSrv, errorHandler, lotteryStatus, lottery) {
Angular's service for working with asynchronous functions

2019-10-16 10:35 UTC, jonaslozys commented on src/webapp/src/client/app/lotteries/lotteries.repository.js
> +            return $resource(url + 'Delete').delete({id}).$promise;
Will rename the endpoint to 'Abort'

2019-10-16 10:36 UTC, jonaslozys commented on src/webapp/src/client/app/lotteries/lottery-list.html
> +                            {{lottery.endDate.replace('T', '  ').substring(0, lottery.endDate.length - 3)}}
Had been updated in further commits

2019-10-16 10:43 UTC, jonaslozys commented on src/webapp/src/client/app/lotteries/lottery-list.controller.js
> +        })
Will add this as a story to Trello

2019-10-16 10:55 UTC, jonaslozys commented on src/webapp/src/client/app/lotteries/lottery-list.controller.js
> +        })
Yes, will fix that

2019-10-16 11:14 UTC, jonaslozys commented on src/webapp/src/client/app/lotteries/lotteries.module.js
> +                    ]
Yes, otherwise the user will be redirected to not authorized page.

2019-11-05 12:44 UTC, merged